### ISSUE TITLE
Cannot get page count.

### ISSUE THREAD

**Issue by SV-stark** [raffaem/pdfsak#16] opened 2022-08-31 08:20 UTC
**Describe the bug**
any pdf file used as input gives error "Cannot get page count" and pdfsak exits 
>ERROR: Cannot get page count.
 cmd: {cmd}
stdout: {res.stdout}
stderr: {res.stderr}

**To Reproduce**

>pdfsak -if outp.pdf -o op.pdf --clearscan 

**Expected behavior**
pdfsak to start processing the file 

**System information**

>os.name: posix
platform.system(): Linux
platform.release(): 5.15.60-1-MANJARO
CWD: /tmp/pdfsak1succ0en
PATH: /home/suyash/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin
Python: 3.10.5 (main, Aug  1 2022, 07:53:20) [GCC 12.1.0]
PDFsak version: 1.3.0
pdflatex OK (1.40.24 >= 1.40.17): pdfTeX 3.141592653-2.6-1.40.24 (TeX Live 2022/Arch Linux)
Checking LaTeX package 'grffile' OK: 2019/11/11 v2.1
Checking LaTeX package 'pdfpages' OK: 2022/01/29 v0.5u
Checking LaTeX package 'lastpage' OK: 2021/09/03 v1.2n
Checking LaTeX package 'fancyhdr' OK: 2021/01/28 v4.0.1
Checking LaTeX package 'geometry' OK: 2020/01/02 v5.9
Checking LaTeX package 'calc' OK: 2017/05/25 v4.3
Checking LaTeX package 'graphicx' OK: 2021/09/16 v1.2d
Checking LaTeX package 'transparent' OK: 2019/11/29 v1.4
Checking LaTeX package 'xparse' OK: 2022-01-12 L3
Checking LaTeX package 'letltxmacro' OK: 2019/12/03 v1.6
Checking LaTeX package 'changepage' OK: 2009/10/20 v1.0c
Checking LaTeX package 'textpos' OK: 2020/09/26 v1.10
ImageMagick OK: Version: ImageMagick 7.1.0-45 Q16-HDRI x86_64 20319 
Potrace OK: 1.16.
mkbitmap OK: 1.16.
Ghostscript OK: 9.56.1

**Comment by raffaem** [comment] 2022-08-31 08:49
Duplicate of #14

**Closed by raffaem** 2022-08-31 08:50 UTC
